apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-experiment
spec:
  replicas: 1
  strategy:
    ################################
    # canary strategy gradually shifts traffic from the baseline to the canary
    ################################
    # canary:
    #   steps:
    #   - setWeight: 20
    #   - pause: {duration: 10}
    #   # リリースの影響を最小限に抑えるため、新しいリリースを一部のユーザーにのみ公開します。
    #   - experiment:
    #       duration: 5m
    #       templates:
    #       - name: canary
    #         specRef: canary
    #       # This experiment performs its own analysis by referencing an AnalysisTemplates
    #       # The success or failure of these runs will progress or abort the rollout respectively.
    #       analyses:
    #       - name: canary-experiment
    #         templateName: webmetric
    #   - setWeight: 40
    #   - pause: {duration: 10}
    #   - setWeight: 60
    #   - pause: {duration: 10}
    #   - setWeight: 80
    #   - pause: {duration: 10}
    ################################
    # A/B testing
    ################################
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 10}
      - setWeight: 50
      - pause: {duration: 10}
      - experiment:
          duration: 3m
          templates:
          - name: canary
            specRef: canary
          analyses:
          - name: canary-experiment
            templateName: webmetric
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: rollout-experiment
  template:
    metadata:
      labels:
        app: rollout-experiment
    spec:
      containers:
      - name: rollouts-demo
        image: asia-northeast1-docker.pkg.dev/test-yokoo/gitops-demo/weather-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: rollout-weather-svc
spec:
  selector:
    app: rollout-experiment
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
  type: LoadBalancer