apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.cd-visibility-trigger.cd-visibility-webhook: ""
    dd_env: staging
    dd_service: memegen
    dd_customtags: "team:japan-se"
spec:
  project: default
  source:
    repoURL: https://github.com/parupappa/gitops-demo.git
    targetRevision: main
    path: memegen-manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true