apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fibonacci
  template:
    metadata:
      labels:
        app: fibonacci
    spec:
      containers:
      - name: fibonacci
        image: asia-northeast1-docker.pkg.dev/test-yokoo/gitops-demo/fibonacci:blue
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: fibonacci-service
spec:
  selector:
    app: fibonacci
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer