apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fibonacci
  template:
    metadata:
      labels:
        app: fibonacci
    spec:
      containers:
      - name: fibonacci
        image: asia-northeast1-docker.pkg.dev/test-yokoo/gitops-demo/memegen:blue
        ports:
        - containerPort: 8080