apiVersion: apps/v1
kind: Deployment
metadata:
  name: memegen-deployment
  labels:
    app: memegen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memegen
  template:
    metadata:
      labels:
        app: memegen
    spec:
      containers:
      - name: memegen
        image: asia-northeast1-docker.pkg.dev/test-yokoo/gitops-demo/memegen:green
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: memegen-service
spec:
  selector:
    app: memegen
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer